-- ==========================================================
-- PŌKAI — Testes físicos: schema + importação
-- Execute no Supabase → SQL Editor. Seguro reexecutar.
-- ==========================================================

-- 1) Colunas de confirmação de treino (tabela logs)
alter table logs add column if not exists fc_media numeric;
alter table logs add column if not exists fc_maxima numeric;
alter table logs add column if not exists calorias numeric;
alter table logs add column if not exists dor text;

-- 2) Gênero no perfil (tabela students)
alter table students add column if not exists genero text;

-- 3) Tabela de testes físicos (histórico)
create table if not exists testes (
  id text primary key,
  student_id text,
  genero text,
  date text,
  provas jsonb,
  fases jsonb,
  pontuacao_geral numeric,
  posicao integer,
  feedback_geral text,
  observacoes text,
  created_at text
);

-- 4) Gênero dos alunos avaliados
update students set genero='F' where id='Valentina Castilho de Araújo Paiva';
update students set genero='F' where id='Gabriella Alencar';
update students set genero='M' where id='Vilson Vedana';
update students set genero='M' where id='Lucas Soares';
update students set genero='M' where id='Rodrigo Barbosa Martins';
update students set genero='M' where id='Gabriel A. N. Andrade';
update students set genero='M' where id='Gustavo Tomás Pereira Santos';
update students set genero='F' where id='Isabela Fioravanti';

-- 5) Importação dos testes (1 registro por aluno por data)
insert into testes (id,student_id,genero,date,provas,fases,pontuacao_geral,posicao,feedback_geral,observacoes,created_at) values (
  'teste_valentina_castilho_de_ara_jo_paiva_2026-05-09', 'Valentina Castilho de Araújo Paiva', 'F', '2026-05-09',
  '[{"id":"banco_wells","valor":32,"feedback":"Wells 32cm é excelente. Melhor flexibilidade feminina da turma."},{"id":"alcance_ombro","valor":7.5,"feedback":"Ombro 7.5cm+ é muito bom, mobilidade saudável."},{"id":"agachamento","valor":60,"feedback":"60kg×5 (quase 1x peso corporal) é forte para o perfil."},{"id":"paralela","valor":0,"feedback":"Corpo×5 com boa forma. Potencial alto para progredir com lastro (+5kg)."},{"id":"barra_fixa","valor":0,"feedback":"#1 equalizada da turma — 4 reps corpo puro como mulher de 64kg é excepcional."},{"id":"flexao","valor":45,"feedback":"45 flexões é bom, mas puxa junto com burpee/canivete a média de resistência."},{"id":"burpee","valor":28,"feedback":"28 reps em 2min — abaixo do potencial. Alvo 35+. Treinar EMOM de burpees."},{"id":"canivete","valor":40,"feedback":"40 reps — treinar hollow body holds e V-up parciais. Alvo 50+."},{"id":"circuito","valor":176,"feedback":"4 rounds completos, segunda melhor da turma. Consistente."}]'::jsonb,
  '{"Flexibilidade":66.7,"Força":96.2,"Resistência":54,"Circuito":79.7}'::jsonb,
  77.1, 2, 'Posição 2 no ranking geral (Score 77.1). Força relativa extraordinária — #1 equalizada em barra fixa fazendo 4 reps corpo puro como mulher de 64kg. Melhor flexibilidade feminina. Circuito consistente com 4 rounds completos. Perfil equilibrado sem fase criticamente fraca. Ponto a desenvolver: resistência muscular (burpee e canivete abaixo do potencial). Recomendações: focar em volume de burpee (EMOM 8-10 burpees/min por 5-8min, 2x/semana, alvo 35+ em 2min); treinar hollow body holds e V-up parciais para canivete (alvo 50+); na paralela buscar lastro começando com +5kg; manter a flexibilidade que já é diferencial.', 'Perfil: idade 29, peso 64kg, altura 167cm. Notas por fase (0-100): Flexibilidade 66.7, Força 96.2, Resistência 54.0, Circuito 79.7. Posição no ranking: 2.', '2026-05-09'
) on conflict (id) do update set provas=excluded.provas, fases=excluded.fases, pontuacao_geral=excluded.pontuacao_geral, posicao=excluded.posicao, feedback_geral=excluded.feedback_geral, observacoes=excluded.observacoes, genero=excluded.genero;

insert into testes (id,student_id,genero,date,provas,fases,pontuacao_geral,posicao,feedback_geral,observacoes,created_at) values (
  'teste_gabriella_alencar_2026-05-09', 'Gabriella Alencar', 'F', '2026-05-09',
  '[{"id":"banco_wells","valor":3,"feedback":"Wells 3cm — abaixo da média. Cadeia posterior travada."},{"id":"alcance_ombro","valor":3.25,"feedback":"Ombro 3.25cm — abaixo da média. Incluir mobilidade pós-treino."},{"id":"agachamento","valor":40,"feedback":"40kg×7 (0.8x BW) com potencial de crescimento. Progredir para 50kg."},{"id":"paralela","valor":-4.5,"feedback":"Elástico azul×5 mostra base sólida. Bom ponto de partida."},{"id":"barra_fixa","valor":0,"feedback":"Corpo×4 — força relativa boa, #2 equalizada."},{"id":"flexao","valor":25,"feedback":"25 flexões em 2min é o menor número da turma. Prioridade máxima. Alvo 40+."},{"id":"burpee","valor":22,"feedback":"22 reps — baixo para o potencial aeróbico que o circuito mostra."},{"id":"canivete","valor":55,"feedback":"55 reps — melhor entre as mulheres. Ponto forte."},{"id":"circuito","valor":222,"feedback":"5 rounds + 2 extras com 50kg! Melhor circuito feminino, #3 geral. Excepcional."}]'::jsonb,
  '{"Flexibilidade":13.2,"Força":92,"Resistência":35.8,"Circuito":77.9}'::jsonb,
  62.6, 7, 'Posição 7 no ranking geral (Score 62.6). Circuito impressionante — 5 rounds + 2 extras com apenas 50kg de peso corporal, melhor circuito feminino e #3 geral, mostra garra e pacing inteligente. Força relativa boa. Canivete forte (55 reps, melhor entre as mulheres). Pontos a desenvolver: resistência de upper body crítica (25 flexões, menor da turma), flexibilidade muito baixa. Recomendações: flexão é prioridade (3-4 séries até falha 3x/semana, incluir inclinadas, alvo 40+); rotina de mobilidade pós-treino (ombro + posterior); progredir agachamento para 50kg (1x BW); treinar tabata de burpees com pacing constante.', 'Perfil: idade 31, peso 50kg, altura 160cm. Notas por fase (0-100): Flexibilidade 13.2, Força 92.0, Resistência 35.8, Circuito 77.9. Posição no ranking: 7.', '2026-05-09'
) on conflict (id) do update set provas=excluded.provas, fases=excluded.fases, pontuacao_geral=excluded.pontuacao_geral, posicao=excluded.posicao, feedback_geral=excluded.feedback_geral, observacoes=excluded.observacoes, genero=excluded.genero;

insert into testes (id,student_id,genero,date,provas,fases,pontuacao_geral,posicao,feedback_geral,observacoes,created_at) values (
  'teste_vilson_vedana_2026-05-09', 'Vilson Vedana', 'M', '2026-05-09',
  '[{"id":"banco_wells","valor":27,"feedback":"27cm é bom para posterior."},{"id":"alcance_ombro","valor":-11.5,"feedback":"-11.5cm indica restrição severa de mobilidade de ombro. Pior da turma. Prioridade."},{"id":"agachamento","valor":97,"feedback":"97kg×5 — força absoluta sólida."},{"id":"paralela","valor":32,"feedback":"+32kg de lastro — nível forte."},{"id":"barra_fixa","valor":20,"feedback":"Com 98.5kg o peso penaliza. Apenas 2 reps com +20kg. Trabalhar volume submax."},{"id":"flexao","valor":60,"feedback":"#1 da turma com 60 reps. Resistência excepcional."},{"id":"burpee","valor":40,"feedback":"#1 da turma com 40 reps."},{"id":"canivete","valor":60,"feedback":"#1 da turma com 60 reps."},{"id":"circuito","valor":176,"feedback":"#1 da turma — 4 rounds completos com 98.5kg. Imbatível."}]'::jsonb,
  '{"Flexibilidade":11,"Força":88.4,"Resistência":100,"Circuito":100}'::jsonb,
  82.6, 1, 'Posição 1 no ranking geral (Score 82.6). Resistência muscular excepcional — #1 em flexão (60), burpee (40) e canivete (60), dominando as três estações. Circuito imbatível — 4 rounds completos com 98.5kg de peso corporal e fator de idade impressionante (45 anos). Força absoluta sólida. Ponto crítico: flexibilidade (11.0/100, pior da turma), com alcance de ombro -11.5cm indicando restrição severa. Recomendações: PRIORIDADE mobilidade de ombro (hang passivo, rotação externa com elástico, stretches de peitoral diários 5-10min, alvo chegar a 0cm em 3 meses); manter base de resistência e circuito que é o diferencial; na barra fixa trabalhar volume submax (3-4 séries de 3 com +10kg).', 'Perfil: idade 45, peso 98.5kg, altura 190cm. Notas por fase (0-100): Flexibilidade 11.0, Força 88.4, Resistência 100.0, Circuito 100.0. Posição no ranking: 1.', '2026-05-09'
) on conflict (id) do update set provas=excluded.provas, fases=excluded.fases, pontuacao_geral=excluded.pontuacao_geral, posicao=excluded.posicao, feedback_geral=excluded.feedback_geral, observacoes=excluded.observacoes, genero=excluded.genero;

insert into testes (id,student_id,genero,date,provas,fases,pontuacao_geral,posicao,feedback_geral,observacoes,created_at) values (
  'teste_lucas_soares_2026-05-09', 'Lucas Soares', 'M', '2026-05-09',
  '[{"id":"banco_wells","valor":27,"feedback":"27cm é forte."},{"id":"alcance_ombro","valor":4.5,"feedback":"4.5cm+ é positivo, boa mobilidade."},{"id":"agachamento","valor":97,"feedback":"97kg×5 (1.26x BW), igual ao Vilson que pesa 21kg a mais. Forte."},{"id":"paralela","valor":32,"feedback":"+32kg de lastro, nível bom."},{"id":"barra_fixa","valor":5,"feedback":"Apenas 5kg lastro com 4 reps. Desproporcional ao agachamento forte. Prioridade."},{"id":"flexao","valor":71,"feedback":"71 reps — melhor número absoluto da turma. #2 equalizado com boost de idade."},{"id":"burpee","valor":32,"feedback":"32 reps — bom, #2 equalizado."},{"id":"canivete","valor":45,"feedback":"45 reps — abaixo do potencial. Incluir L-sits e toes-to-bar."},{"id":"circuito","valor":144,"feedback":"3 rounds + 12 extras. Com 77kg deveria fazer mais dado o nível de resistência."}]'::jsonb,
  '{"Flexibilidade":63.2,"Força":87,"Resistência":66.6,"Circuito":59.7}'::jsonb,
  71.5, 4, 'Posição 4 no ranking geral (Score 71.5). Melhor flexão da turma — 71 reps em 2min, o número mais alto absoluto, e com boost de idade (38a, +6.5%) fica #2 equalizado. Boa flexibilidade. Agachamento pesado — 97kg×5 (1.26x BW), igual ao Vilson que pesa 21kg a mais. Equilíbrio entre fases. Pontos a desenvolver: circuito (3 rounds + 12 extras, deveria fazer mais), barra fixa fraca (só 5kg lastro com 4 reps, desproporcional ao agachamento). Recomendações: barra fixa é prioridade (weighted pull-ups progressivos, 3-4 séries de 5 com +10kg, +2.5kg/semana, alvo +15kg×5 em 2 meses); praticar o circuito específico 1x/mês; incluir L-sits e toes-to-bar para canivete.', 'Perfil: idade 38, peso 77kg, altura 175cm. Notas por fase (0-100): Flexibilidade 63.2, Força 87.0, Resistência 66.6, Circuito 59.7. Posição no ranking: 4.', '2026-05-09'
) on conflict (id) do update set provas=excluded.provas, fases=excluded.fases, pontuacao_geral=excluded.pontuacao_geral, posicao=excluded.posicao, feedback_geral=excluded.feedback_geral, observacoes=excluded.observacoes, genero=excluded.genero;

insert into testes (id,student_id,genero,date,provas,fases,pontuacao_geral,posicao,feedback_geral,observacoes,created_at) values (
  'teste_rodrigo_barbosa_martins_2026-05-09', 'Rodrigo Barbosa Martins', 'M', '2026-05-09',
  '[{"id":"banco_wells","valor":6,"feedback":"6cm — cadeia posterior com restrição."},{"id":"alcance_ombro","valor":9.5,"feedback":"9.5cm+ simétrico (ambos lados iguais), boa mobilidade de ombro."},{"id":"agachamento","valor":86,"feedback":"#1 equalizado — 86kg×11 reps, Epley ~118kg (1.42x BW). No próximo teste buscar carga maior e parar em 5 reps."},{"id":"paralela","valor":44,"feedback":"#1 equalizado — +44kg de lastro com 83kg é nível avançado."},{"id":"barra_fixa","valor":29,"feedback":"Apenas 2 reps com +29kg vs 5 reps com +44kg na paralela. Pull muito mais fraco que push. Risco de lesão."},{"id":"flexao","valor":60,"feedback":"60 reps — bom."},{"id":"burpee","valor":20,"feedback":"20 reps em 2min — pior da turma. Prioridade absoluta. Derruba a resistência."},{"id":"canivete","valor":40,"feedback":"40 reps."},{"id":"circuito","valor":134,"feedback":"3 rounds + 2 extras. Não condiz com a força que tem."}]'::jsonb,
  '{"Flexibilidade":40.6,"Força":92.5,"Resistência":54.8,"Circuito":57.8}'::jsonb,
  66.6, 5, 'Posição 5 no ranking geral (Score 66.6). #1 equalizado em agachamento — 86kg×11 reps, volume impressionante, Epley estima 1RM de ~118kg (1.42x BW). #1 equalizado em paralela — +44kg de lastro com 83kg de BW é nível avançado. Força geral alta, top 3. Pontos críticos: burpee (20 reps, pior da turma) derruba a resistência; circuito fraco; Wells baixo; barra fixa desproporcional (2 reps com +29kg vs 5 reps com +44kg na paralela, pull muito mais fraco que push). Recomendações: PRIORIDADE ABSOLUTA burpee e condicionamento (o gap força/resistência é o maior da turma, 2 sessões/semana de metcon); treinar volume de pull-ups para corrigir desequilíbrio push/pull (risco de lesão de ombro); stretches de posterior; no próximo teste buscar carga mais pesada no agachamento e parar em 5 reps.', 'Perfil: idade 31, peso 83kg, altura 174cm. Notas por fase (0-100): Flexibilidade 40.6, Força 92.5, Resistência 54.8, Circuito 57.8. Posição no ranking: 5.', '2026-05-09'
) on conflict (id) do update set provas=excluded.provas, fases=excluded.fases, pontuacao_geral=excluded.pontuacao_geral, posicao=excluded.posicao, feedback_geral=excluded.feedback_geral, observacoes=excluded.observacoes, genero=excluded.genero;

insert into testes (id,student_id,genero,date,provas,fases,pontuacao_geral,posicao,feedback_geral,observacoes,created_at) values (
  'teste_gabriel_a_n_andrade_2026-05-09', 'Gabriel A. N. Andrade', 'M', '2026-05-09',
  '[{"id":"banco_wells","valor":10,"feedback":"10cm."},{"id":"alcance_ombro","valor":0.25,"feedback":"0.25cm — quase zero. Alerta funcional. Com a força de upper body, risco alto de lesão de ombro. Prioridade crítica."},{"id":"agachamento","valor":74,"feedback":"74kg×11. #2 equalizado. No próximo teste buscar 90kg+ em 5 reps."},{"id":"paralela","valor":44,"feedback":"MAIOR nota de força da turma. +44kg com 74kg = 1.59x BW em dip. #1 equalizado."},{"id":"barra_fixa","valor":29,"feedback":"+29kg×7 reps — força-resistência de pull excepcional."},{"id":"flexao","valor":64,"feedback":"64 reps — forte."},{"id":"burpee","valor":23,"feedback":"23 reps — baixo. O condicionamento não acompanha a força. Treinar especificamente."},{"id":"canivete","valor":50,"feedback":"50 reps — forte, top 3."},{"id":"circuito","valor":148,"feedback":"3 rounds + 16 extras. Não condiz com o nível de força."}]'::jsonb,
  '{"Flexibilidade":18.1,"Força":98.8,"Resistência":56,"Circuito":57}'::jsonb,
  65.5, 6, 'Posição 6 no ranking geral (Score 65.5). MAIOR NOTA DE FORÇA DA TURMA (98.8/100) — paralela +44kg com 74kg de BW = 1.59x BW em dip; barra +29kg×7 reps mostra força-resistência de pull excepcional. Melhor relação força/peso da turma. Canivete forte (50 reps). Pontos críticos: flexibilidade péssima (18.1/100, ombro 0.25cm quase zero) — alerta funcional com risco alto de lesão de ombro dada a força de upper body; resistência geral fraca (burpee 23); circuito não condiz com o nível de força. Recomendações: PRIORIDADE CRÍTICA mobilidade de ombro (com 98.8 de força e 18.1 de flex o risco de lesão é real; rotina diária mínimo 10min: hang passivo 3×30s, peitoral door stretch, rotação externa com band); condicionamento aeróbico 2x/semana (AMRAP/EMOM 8-12min); treinar burpee especificamente; no próximo teste agachamento em 5 reps com carga maior (buscar 90kg+).', 'Perfil: idade 31, peso 74kg, altura 175cm. Notas por fase (0-100): Flexibilidade 18.1, Força 98.8, Resistência 56.0, Circuito 57.0. Posição no ranking: 6.', '2026-05-09'
) on conflict (id) do update set provas=excluded.provas, fases=excluded.fases, pontuacao_geral=excluded.pontuacao_geral, posicao=excluded.posicao, feedback_geral=excluded.feedback_geral, observacoes=excluded.observacoes, genero=excluded.genero;

insert into testes (id,student_id,genero,date,provas,fases,pontuacao_geral,posicao,feedback_geral,observacoes,created_at) values (
  'teste_gustavo_tom_s_pereira_santos_2026-05-09', 'Gustavo Tomás Pereira Santos', 'M', '2026-05-09',
  '[{"id":"banco_wells","valor":3,"feedback":"3cm — contrasta com o ótimo ombro. Cadeia posterior travada. Prioridade."},{"id":"alcance_ombro","valor":15.75,"feedback":"#1 absoluto da turma com 15.75cm. Mobilidade de ombro excepcional."},{"id":"agachamento","valor":86,"feedback":"86kg×5 — sólido."},{"id":"paralela","valor":44,"feedback":"+44kg — número de elite. #2 da turma."},{"id":"barra_fixa","valor":29,"feedback":"+29kg×6 — nível de elite. #3 da turma."},{"id":"flexao","valor":65,"feedback":"65 reps — forte."},{"id":"burpee","valor":26,"feedback":"26 reps — ponto mais fraco em resistência. Treinar intervalos."},{"id":"canivete","valor":50,"feedback":"50 reps."},{"id":"circuito","valor":176,"feedback":"4 rounds com 82kg. Forte."}]'::jsonb,
  '{"Flexibilidade":55.2,"Força":93.3,"Resistência":65.5,"Circuito":76.5}'::jsonb,
  76.4, 3, 'Posição 3 no ranking geral (Score 76.4). Força superior (93.3/100) — paralela com +44kg e barra com +29kg×6 são números de elite em calistenia. #1 absoluto em alcance de ombro (15.75cm!), mobilidade excepcional. Circuito forte (4 rounds com 82kg). Bom equilíbrio geral. Pontos a desenvolver: Wells muito baixo (3cm, contrasta com o ótimo ombro, cadeia posterior travada); burpee fraco (26 reps). Recomendações: PRIORIDADE flexibilidade posterior (good mornings com barra, Jefferson curls, stretches de isquiotibiais diários, alvo 15cm+ no Wells em 3 meses); burpee em intervalos (30s on/30s off por 5-8min, 2x/semana); manter a força buscando paralela +50kg e barra +35kg.', 'Perfil: idade 31, peso 82kg, altura 182cm. Notas por fase (0-100): Flexibilidade 55.2, Força 93.3, Resistência 65.5, Circuito 76.5. Posição no ranking: 3.', '2026-05-09'
) on conflict (id) do update set provas=excluded.provas, fases=excluded.fases, pontuacao_geral=excluded.pontuacao_geral, posicao=excluded.posicao, feedback_geral=excluded.feedback_geral, observacoes=excluded.observacoes, genero=excluded.genero;

insert into testes (id,student_id,genero,date,provas,fases,pontuacao_geral,posicao,feedback_geral,observacoes,created_at) values (
  'teste_isabela_fioravanti_2026-05-09', 'Isabela Fioravanti', 'F', '2026-05-09',
  '[{"id":"banco_wells","valor":25,"feedback":"25cm é sólido. Provavelmente top 3 feminino."},{"id":"alcance_ombro","valor":5.25,"feedback":"5.25cm+ indica mobilidade saudável."},{"id":"agachamento","valor":52,"feedback":"52kg×10 mostra boa capacidade de volume em lower body."},{"id":"paralela","valor":-9.5,"feedback":"Elástico roxo×5 mostra gap em upper body. Reduzir assistência progressivamente."},{"id":"barra_fixa","valor":-27,"feedback":"Preto+roxo (~27kg de assistência) para 5 reps. Meta: reduzir a assistência progressivamente com negativos lentos."},{"id":"flexao","valor":19,"feedback":"19 reps em 2min — menor número absoluto da turma. Fraqueza significativa em upper body push. Prioridade 1. Alvo 30+."},{"id":"burpee","valor":21,"feedback":"21 reps."},{"id":"canivete","valor":50,"feedback":"50 reps — competitivo com a turma. Ponto forte."},{"id":"circuito","valor":88,"feedback":"Apenas 2 rounds. Condicionamento geral precisa de desenvolvimento."}]'::jsonb,
  null,
  null, null, 'Score pendente — faltam idade, peso e altura para calcular. Análise pelos dados brutos: Flexibilidade boa (Wells 25cm sólido, ombro 5.25cm+ mobilidade saudável, provavelmente top 3 feminino em flex). Canivete forte (50 reps, competitivo). Agachamento com potencial (52kg×10, boa capacidade de volume). Pontos a desenvolver: flexão muito baixa (19 reps, menor absoluto da turma, fraqueza em upper body push); circuito fraco (2 rounds); barra fixa com assistência alta (preto+roxo ~27kg para 5 reps); paralela com assistência (roxo). Recomendações: PRIORIDADE 1 força de upper body (flexão em volume até falha, incluir inclinada e negativa, alvo 30+ em 2min); PRIORIDADE 2 barra fixa (progredir de preto+roxo para apenas preto, depois roxo, depois corpo; negativos lentos 5s 3-4x/semana); circuito (AMRAPs de 10min 1x/semana, trabalhar pacing); manter a flexibilidade que já é ponto forte.', 'Perfil incompleto: falta idade, peso e altura (solicitados ao aluno). Score geral e notas por fase não calculados por dependerem do perfil.', '2026-05-09'
) on conflict (id) do update set provas=excluded.provas, fases=excluded.fases, pontuacao_geral=excluded.pontuacao_geral, posicao=excluded.posicao, feedback_geral=excluded.feedback_geral, observacoes=excluded.observacoes, genero=excluded.genero;

